/scriptA:
  ros__parameters: 
    queue_data:
      queue_1:
        entries:
        - grid_1
        - grid_2
        feeding:
          X: 8
          Y: 4
          theta: 1.57
        grid_1:
          X: 7
          Y: 4
          dir: (0,0,3,0)
          theta: 0
        grid_2:
          X: 7
          Y: 4
          dir: (0,0,3,0)
          theta: 0
      queue_2:
        entries:
        - grid_1
        feeding:
          X: 7
          Y: 33
          theta: -1.57
        grid_1:
          X: 8
          Y: 33
          dir: (0,0,0,4)
          theta: 3.14
      queue_3:
        entries:
        - grid_1
        feeding:
          X: 12
          Y: 4
          theta: 1.57
        grid_1:
          X: 11
          Y: 4
          dir: (0,0,3,0)
          theta: 0
      queue_4:
        entries:
        - grid_1
        feeding:
          X: 10
          Y: 4
          theta: 1.57
        grid_1:
          X: 9
          Y: 4
          dir: (0,0,3,0)
          theta: 0
      queue_5:
        entries:
        - grid_1
        feeding:
          X: 9
          Y: 33
          theta: -1.57
        grid_1:
          X: 10
          Y: 33
          dir: (0,0,0,4)
          theta: 3.14
      queue_6:
        entries:
        - grid_1
        feeding:
          X: 11
          Y: 33
          theta: -1.57
        grid_1:
          X: 12
          Y: 33
          dir: (0,0,0,4)
          theta: 3.14
