/stateManager:
  ros__parameters: 
    robots_number: 1
    extra_robots: 1
    map_synthesis:
      dump_grids_direction: vertical
      dump_in_reverse: true
      grid_size: 0.6
      height: 36
      offset: 0.3
      width: 16
      test_attribute:
        nested_test_1: 12
        nested_test_2: "string"
        nested_test_3: 0.7